language: go
sudo: false
dist: bionic
osx_image: xcode10
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

os:
  - linux
  - osx
  - windows

env:
  GO111MODULE=on

cache:
  directories:
    - node_modules

before_script:
  - go get github.com/shurcooL/vfsgen || true
  - go get github.com/shurcooL/httpfs/union || true
  - go get github.com/urfave/gfmrun/... || true
  - go get golang.org/x/tools/cmd/goimports
  - npm install markdown-toc

script:
  - go run build.go generate
  - go run build.go vet
  - go run build.go testm
  - go run build.go gfmrun
  - go run build.go toc

after_success:
  - bash <(curl -s https://codecov.io/bash)
