language: go
sudo: false
dist: trusty

cache:
  directories:
  - node_modules

go: 1.8.x

matrix:
  include:
  - go: 1.8.x
    os: osx
    osx_image: xcode8.3

before_script:
- go get github.com/urfave/gfmrun/... || true
- go get golang.org/x/tools/cmd/goimports
- if [ ! -f node_modules/.bin/markdown-toc ] ; then
    npm install markdown-toc ;
  fi

script:
- ./runtests gen
- ./runtests vet
- ./runtests test
- ./runtests gfmrun
- ./runtests toc
