language: go

sudo: false

cache:
  directories:
  - node_modules

go:
- 1.2.2
- 1.3.3
- 1.4
- 1.5.4
- 1.6.2
- master

env: pip_install="pip install --user"

matrix:
  allow_failures:
  - go: master
  include:
  - go: 1.6.2
    os: osx
    env: pip_install="sudo pip install"
  - go: 1.1.2
    install: go get -v .
    before_script: echo skipping gfmxr on ${TRAVIS_GO_VERSION}
    script:
    - ./runtests vet
    - ./runtests test

before_script:
- $pip_install flake8
- if [ ! -f node_modules/.bin/markdown-toc ] ; then
    npm install markdown-toc ;
  fi
- mkdir -p ${GOPATH%%:*}/src/gopkg.in/urfave
- rm -rvf ${GOPATH%%:*}/src/gopkg.in/urfave/cli.v2
- ln -sv ${TRAVIS_BUILD_DIR} ${GOPATH%%:*}/src/gopkg.in/urfave/cli.v2
- go get github.com/urfave/gfmxr/...

script:
- flake8 runtests cli-v1-to-v2
- ./runtests vet
- ./runtests test
- ./runtests gfmxr
- ./cli-v1-to-v2 --selftest
- ./runtests migrations
- ./runtests toc
