language: go

sudo: false

cache: pip

go:
- 1.2.2
- 1.3.3
- 1.4
- 1.5.4
- 1.6.2
- master

matrix:
  allow_failures:
  - go: master
  include:
  - go: 1.6.2
    os: osx
  - go: 1.1.2
    install: go get -v .
    before_script: echo skipping gfmxr on $TRAVIS_GO_VERSION
    script:
    - ./runtests vet
    - ./runtests test

before_script:
- go get github.com/urfave/gfmxr/...
- pip install --user flake8
- if [ -d ~/Library/Python ] ; then
    export PATH=$PATH:$(dirname $(find ~/Library/Python -name flake8)) ;
  fi
- mkdir -p .extracted-examples
- curl -sSL -o .extracted-examples/README.md
    'https://raw.githubusercontent.com/urfave/cli/v1/README.md'
- pushd .extracted-examples && gfmxr extract -o . ; popd

script:
- flake8 runtests cli-v1-to-v2
- ./runtests vet
- ./runtests test
- ./runtests gfmxr
- ./cli-v1-to-v2 --selftest
- for f in .extracted-examples/*.go ; do
    ./cli-v1-to-v2 -w $f ;
    go build -o .extracted-examples/example $f ;
    ./cli-v1-to-v2 -w $f ;
    go build -o .extracted-examples/example $f ;
  done
