language: go
sudo: false
dist: trusty
osx_image: xcode8.3
go: 1.11.x

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

before_script:
  - go get github.com/urfave/cli/flag-gen || true
  - go get github.com/shurcooL/vfsgen || true
  - go get github.com/shurcooL/httpfs/union || true
  - go get github.com/urfave/gfmrun/... || true
  - go get golang.org/x/tools/cmd/goimports
  - if [ ! -f node_modules/.bin/markdown-toc ] ; then
    npm install markdown-toc ;
    fi

script:
  #- go generate ./... # to be uncommented after merge as we cannot compile the package which is not present in master
  - ./runtests vet
  - ./runtests test
  - ./runtests gfmrun
  - ./runtests toc

after_success:
  - ./coverage.sh
  - bash <(curl -s https://codecov.io/bash)
