language: go
sudo: false
dist: trusty
osx_image: xcode8.3
go: 1.11.x

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

before_script:
  - go get github.com/shurcooL/vfsgen || true
  - go get github.com/shurcooL/httpfs/union || true
  - go get github.com/urfave/gfmrun/... || true
  - go get golang.org/x/tools/cmd/goimports
  - if [ ! -f node_modules/.bin/markdown-toc ] ; then
    npm install markdown-toc ;
    fi

script:
  - go run build/build.go generate
  - go run build/build.go vet
  - go run build/build.go test
  - go run build/build.go gfmrun
  - go run build/build.go toc

after_success:
  - bash <(curl -s https://codecov.io/bash)
