version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\urfave\cli

cache:
- node_modules

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.6
  PYTHON: C:\Python27-x64
  PYTHON_VERSION: 2.7.x
  PYTHON_ARCH: 64
  GFMXR_DEBUG: 1

install:
- set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
- go version
- go env
- git clone . c:\gopath\src\gopkg.in\urfave\cli.v2
- go get github.com/urfave/gfmxr/...
- go get -v -t ./...
- ps: Install-Product node 6
- ps: $MarkdownTocExists = Test-Path node_modules\.bin\markdown-toc
- ps: if ($MarkdownTocExists -eq $False) { npm install markdown-toc }

build_script:
- python runtests vet
- python runtests test
- python runtests gfmxr
- python cli-v1-to-v2 --selftest
- python runtests migrations
- python runtests toc
