version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\urfave\cli

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.6

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/urfave/gfmxr/...
  - go get -v -t ./...

build_script:
  - ./runtests vet
  - ./runtests test
  - ./runtests gfmxr

test: off

deploy: off
