version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\urfave\cli

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.6
  PYTHON: C:\Python27-x64
  PYTHON_VERSION: 2.7.x
  PYTHON_ARCH: 64
  GFMXR_DEBUG: 1

install:
- set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
- go version
- go env
- mkdir c:\gopath\src\gopkg.in\urfave
- (robocopy c:\gopath\src\github.com\urfave\cli c:\gopath\src\gopkg.in\urfave\cli.v2
      /DCOPY:DA /MIR /FFT /Z /XA:SH /R:0 /TEE /XJD) ^& IF %ERRORLEVEL% LEQ 4 exit 0
- go get github.com/urfave/gfmxr/...
- go get -v -t ./...

build_script:
- python runtests vet
- python runtests test
- python runtests gfmxr
- python cli-v1-to-v2 --selftest
- python runtests migrations
- python runtests toc
