name: Run Tests

on:
  pull_request:
    branches:
      master

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.11, 1.12, 1.13]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: |
          go get github.com/urfave/gfmrun/cmd/gfmrun
          go get golang.org/x/tools/cmd/goimports
          go get ./...
          npm install markdown-toc

      - name: Run Tests
        run: |
          ls -la
          go run build.go vet
          go run build.go test
          go run build.go gfmrun docs/v2/manual.md
          go run build.go toc docs/v2/manual.md
